name: Update TryHackMe Badge

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate TryHackMe badge
        uses: geeekgod/tryhackme-badge-action@v1.0
        with:
          username: 'CyberCracker27'          # Replace with your THM username
          user_id: '6767ff388eeda5e1981e450f'                  # Find this in your profile URL
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add badge.svg
          git diff --staged --quiet || git commit -m "Update TryHackMe badge"
          git push
